const express = require("express");
const authRoutes = require("./auth.routes");
const restaurantRoutes = require("./restaurant.routes");
const categoryRoutes = require("./category.routes");
const itemRoutes = require("./item.routes");
const uploadRoutes = require("./upload.routes");
const analyticsRoutes = require('./analytics.routes');
const planRoutes = require("./plan.routes");
const userRoutes = require("./user.routes");
const router = express.Router();

router.use("/auth", authRoutes);
router.use("/restaurant", restaurantRoutes);        
router.use("/categories", categoryRoutes);
router.use("/items", itemRoutes);
router.use("/upload", uploadRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/plans', planRoutes);
router.use('/users', userRoutes);
module.exports = router;
